// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdXcD_wEcnCSYC7pLz1TNjo4qk6X_bcyI',
    appId: '1:96411862307:web:b2c70e23af354ad0e07896',
    messagingSenderId: '96411862307',
    projectId: 'reviewer-70fc0',
    authDomain: 'reviewer-70fc0.firebaseapp.com',
    storageBucket: 'reviewer-70fc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACT3-KxedlGV1qUREZZX0EieuYc6K9RY',
    appId: '1:96411862307:android:78dbe4b6af4acbffe07896',
    messagingSenderId: '96411862307',
    projectId: 'reviewer-70fc0',
    storageBucket: 'reviewer-70fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4quOwrSzTwoBoJF4zt3AbLHoYm2V2GA',
    appId: '1:96411862307:ios:f3342baaf15a8dfce07896',
    messagingSenderId: '96411862307',
    projectId: 'reviewer-70fc0',
    storageBucket: 'reviewer-70fc0.appspot.com',
    iosClientId: '96411862307-dqhhehk8cme4i87bg1o8eoc5frlphb5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4quOwrSzTwoBoJF4zt3AbLHoYm2V2GA',
    appId: '1:96411862307:ios:f3342baaf15a8dfce07896',
    messagingSenderId: '96411862307',
    projectId: 'reviewer-70fc0',
    storageBucket: 'reviewer-70fc0.appspot.com',
    iosClientId: '96411862307-dqhhehk8cme4i87bg1o8eoc5frlphb5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdXcD_wEcnCSYC7pLz1TNjo4qk6X_bcyI',
    appId: '1:96411862307:web:9b6f1ed89908a9a5e07896',
    messagingSenderId: '96411862307',
    projectId: 'reviewer-70fc0',
    authDomain: 'reviewer-70fc0.firebaseapp.com',
    storageBucket: 'reviewer-70fc0.appspot.com',
  );

}